/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StudyInChar123countryChar125RouteImport } from './routes/study-in-{$country}'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as VideosRouteImport } from './routes/videos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyInChar123countryChar125Route =
  StudyInChar123countryChar125RouteImport.update({
    id: '/study-in-{$country}',
    path: '/study-in-{$country}',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/offers': typeof OffersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-in-{$country}': typeof StudyInChar123countryChar125Route
  '/terms-of-use': typeof TermsOfUseRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/offers': typeof OffersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-in-{$country}': typeof StudyInChar123countryChar125Route
  '/terms-of-use': typeof TermsOfUseRoute
  '/videos': typeof VideosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/offers': typeof OffersRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/study-in-{$country}': typeof StudyInChar123countryChar125Route
  '/terms-of-use': typeof TermsOfUseRoute
  '/videos': typeof VideosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/destinations'
    | '/offers'
    | '/privacy-policy'
    | '/services'
    | '/sitemap.xml'
    | '/study-in-{$country}'
    | '/terms-of-use'
    | '/videos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/destinations'
    | '/offers'
    | '/privacy-policy'
    | '/services'
    | '/sitemap.xml'
    | '/study-in-{$country}'
    | '/terms-of-use'
    | '/videos'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/destinations'
    | '/offers'
    | '/privacy-policy'
    | '/services'
    | '/sitemap.xml'
    | '/study-in-{$country}'
    | '/terms-of-use'
    | '/videos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRoute
  OffersRoute: typeof OffersRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudyInChar123countryChar125Route: typeof StudyInChar123countryChar125Route
  TermsOfUseRoute: typeof TermsOfUseRoute
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-in-{$country}': {
      id: '/study-in-{$country}'
      path: '/study-in-{$country}'
      fullPath: '/study-in-{$country}'
      preLoaderRoute: typeof StudyInChar123countryChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRoute,
  OffersRoute: OffersRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudyInChar123countryChar125Route: StudyInChar123countryChar125Route,
  TermsOfUseRoute: TermsOfUseRoute,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
